spring.ai.openai.api-key=sk-fa1de13ce57247588b4ce5d841620b35
spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-chat
spring.ai.openai.chat.options.temperature=0.7

logging.level.org.springframework.ai.chat.client.advisor=DEBUG